# Generated by Django 4.2.28 on 2026-02-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='asset/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
