# Generated by Django 4.2.28 on 2026-02-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_priority', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_priority'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('display_priority', models.IntegerField(default=0)),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('secondary_cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('summary', models.TextField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='projects', to='abra.category')),
            ],
        ),
    ]
